### ISSUE TITLE
EventPluginRegistry Error when declaring within the render 

### ISSUE THREAD

**Issue by avinanda** [mukeshsoni/react-telephone-input#101]
Hello, 

I am new in the react native world so this might be a silly mistake from my part but I keep getting the error: "Cannot inject event plugin more than once." when declaring within the render method. I did npm install and have the library in my node_modules folder. Do you know how I can resolve this issue ? Thank you in advance!

render(){
        **var ReactTelInput = require('react-telephone-input');**   <= here
        return(
        
               <MyAwesomeReactComponent>
<ReactTelInput
        defaultCountry="in"
        flagsImagePath='/path/to/images/flags.png'
        onChange={handleInputChange}
        onBlur={handleInputBlur}
        />
</MyAwesomeReactComponent>

               <TouchableNativeFeedback 
                 onPress={() => this.validatePhoneForm(this.state.phoneNo)}
                 background={TouchableNativeFeedback.SelectableBackground()}>
                    <View style={styles.button}>
                         <Text style={styles.buttonText}>{I18n.t('submit')}</Text>
                    </View>
               </TouchableNativeFeedback>
            </View>
            </View>
        );
    }
}

**Comment by mukeshsoni** [comment]
Hi @avinanda, i do not have enough experience with react native to help you out here. Seems like a react native specific thing. I did once see a similar component built specifically for react native.
