### ISSUE TITLE
Consider manipulating internal value as e164

### ISSUE THREAD

**Issue by benjamindulau** [mukeshsoni/react-telephone-input#102]
I think it could be interesting to manipulate the internal phone number value as an e164 compliant string and use localized formatting only for display.

In almost every project (at least in mine) the server expects e164 values for phone numbers. So it would be really convenient if the onChange callback could optionally receive directly a value as e164 :)

Thoughts?

**Comment by halt-hammerzeit** [comment]
Check out `react-phone-number-input`: it manipulates value as an e164 compliant string
http://halt-hammerzeit.github.io/react-phone-number-input/
And tell me what you think.

**Comment by mukeshsoni** [comment]
@benjamindulau Can you elaborate a little? From what i could find, E164 seems like the format with a + followed by country code and then the number. That is what you get in the formattedNumber property in onChange listener. Am i missing something here?

**Comment by mukeshsoni** [comment]
As far as i understood, our formatted numbers are already E164. We might not be doing a complete validation for E164, but that's on purpose. There's is no good way to programatically validate the E164 format anyways. Need to use something like an external api, like https://www.twilio.com/blog/2017/03/phone-number-verification-without-regular-expression.html, to verify a phone number. That can be done using the isValid prop.
