### ISSUE TITLE
When typing CA number, flag switches to US

### ISSUE THREAD

**Issue by jmaitrehenry** [mukeshsoni/react-telephone-input#103]
Hi,

Each time I click on Canada flag, the US flag take place. How can I choose canada? I tested it with  react-telephone-input 3.5+ and 3.7+

My phone field:
```
const phoneField = <TelInput
      name='phone'
      defaultCountry='mt'
      flagsImagePath='/img/flags.png'
      onChange={(phone, country) => this.setState({ phone, country })}
      value={this.state.phone}
    />
```
Thanks

**Comment by jurgenzz** [comment]
This is a "memoize" ~~issue~~, as it saves "+1" country code in memory as US. If you typed, for example, +1 403 (iso + area code), at the moment the flag should change to CA (haven't checked current version, i have it little bit modified on my environment). 

I'd say we should get rid of memoize there at all (guessSelectedCountry). But yes, i have the same issue and don't really like it.

**Comment by mukeshsoni** [comment]
@jurgenzz Aha! Maybe we should use memoize from npm (https://www.npmjs.com/package/memoizee)). Lodash's memoize only memoizes on one parameter.

**Comment by mukeshsoni** [comment]
scratch that. That memoization is on a single param only.

**Comment by mukeshsoni** [comment]
@jmaitrehenry I have removed the memoize wrapper for guessSelectedCountry now. But have not made a release. Can you please pull the latest code and check it out?

**Comment by mukeshsoni** [comment]
@jmaitrehenry @jurgenzz 
I have removed memoize in v4.0.1.

**Comment by adc17** [comment]
I'm also experiencing this issue.
