### ISSUE TITLE
Can't turn off autoComplete

### ISSUE THREAD

**Issue by skrywus** [mukeshsoni/react-telephone-input#106]
`autoComplete: 'tel',`
Should be possible to set this option as "off".

**Comment by msonip** [comment]
Hi @skrywus. Thanks for the input. Will add that ability in the next release. Will keep you posted.

**Comment by mukeshsoni** [comment]
Hi @skrywus. Thanks for the input. Will add that ability in the next release. Will keep you posted.

**Comment by mukeshsoni** [comment]
@skrywus You can pass the `autoComplete` prop in v4.0.1
