### ISSUE TITLE
Can't display hint text

### ISSUE THREAD

**Issue by Pranav1210** [mukeshsoni/react-telephone-input#107]
I can't show hint text for user. Input has a placeholder 

http://www.w3schools.com/tags/att_input_placeholder.asp

**Comment by msonip** [comment]
Thanks for the bug report. For some reason, i am taking the place holder from the state. Will be fixed in the next release

**Comment by mukeshsoni** [comment]
@Pranav1210 Has been fixed in v4.1.1. Can you please verify?
