### ISSUE TITLE
Add key prop

### ISSUE THREAD

**Issue by Zwem** [mukeshsoni/react-telephone-input#111]
Add please key prop. It need when you use array of react-telephone-input. Thank you

**Comment by mukeshsoni** [comment]
what if you wrap each call to ReactTelephoneInput in an empty div and pass key to that?

```
// numbers is an array
numbers.map(function(number, index) {
  return (
    <div key={index}>
        <ReactTelephoneInput value={number} />
    </div>
  )
})
```

**Comment by Zwem** [comment]
@mukeshsoni  yes, i have code like this, but i think better if i have possibility use prop

**Comment by mukeshsoni** [comment]
I still think adding key is left to the consumer of the component. Closing this one.
