### ISSUE TITLE
Automatically detect country based on location

### ISSUE THREAD

**Issue by reyesreg** [mukeshsoni/react-telephone-input#113]
Been looking at old issues and PRs and this hasn't been asked yet. How can we get default country using user's location?

**Comment by neekey** [comment]
@reyesreg my opinion, it shouldn't be this component's concern

**Comment by mukeshsoni** [comment]
agree with @neekey . Making the component too smart introduces unnecessary complexity which is better taken care of at the site of consumption (whoever uses the component).

**Comment by newswim** [comment]
There appears to be a default prop:

```js
<ReactTelephoneInput
       defaultCountry="us"
       preferredCountries={["us", "ca", "zz", "hk"]}
       flagsImagePath="/assets/images/flags.png">
```

**Comment by mukeshsoni** [comment]
@newswim that prop still needs user input (the component user) to set the default country. What @reyesreg needs is that the component pick the country by detecting user's location

**Comment by newswim** [comment]
Ah right, my fault for not reading the entire issue!

**Comment by newswim** [comment]
This doesn't look terribly difficult to do with the Geolocation api and a call to google to get the country.

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by newswim** [comment]
Oh, except that it only works in Chrome :(

**Comment by mukeshsoni** [comment]
yeah, this one should not be this component's concern. No point doing too much. I will close this.
