### ISSUE TITLE
numbers are typed in randomnly -samsung galaxy s7

### ISSUE THREAD

**Issue by SA21** [mukeshsoni/react-telephone-input#118]
Hi,
we are using react-telephone-input ,and when we type in the numbers in phone field on galaxy s7, the numbers are typed in randomly. 

Expected result: +1(567) 089-9005
Actual Result: +1(765)089-5009

Can anyone help me on this?

 Note: chrome browser and any samsung device

**Comment by newswim** [comment]
I recently got an S7 and will test this out.

**Comment by SA21** [comment]
Let me know if that works for you..Thanks

**Comment by MaxInMoon** [comment]
@newswim any news on it?

**Comment by newswim** [comment]
Apologies, I haven't actually gotten the phone yet -- should be receiving it in the next couple of days.

**Comment by mukeshsoni** [comment]
@SA21 did you find a fix?

**Comment by SA21** [comment]
Not yet. We are still having issues.

**Comment by mukeshsoni** [comment]
@SA21 can you share a gif or a video of the issue?

**Comment by ekwalker** [comment]
We have noticed the same issue lately on Android phones using Chrome.  I've seen a few other reports to issues with cursor positioning on Android Chrome in the past few months as well.  Here's one such issue, and their workaround: https://github.com/necolas/react-native-web/pull/492

**Comment by mukeshsoni** [comment]
@ekwalker Thank you for putting up the link to the browser bug as well as the video. 

So is it a bug with the browser even in the case of the S7 phone?

**Comment by ekwalker** [comment]
@mukeshsoni Yes, I believe it's a bug specific to Android OS using Chrome, where setSelectionRange does not behave properly.

**Comment by ekwalker** [comment]
After digging in more, it actually doesn't seem to be related to setSelectionRange.  The bug occurs every time the number is re-formatted via the pattern passed in to formatNumber.

For example, if the input currently says "+12" and I type in "3", the 3 will go in correctly as "+12 3", but the cursor position will remain before the 3.  So then if you input "4", you will now have "+12 43", which is no longer correct.  

This also happens when the formatting inserts parenthesis or hyphens.

**Comment by mukeshsoni** [comment]
But if it works on desktop, that means it is not a problem with `formatNumber` function but a problem with DOM API in the mobile browser, right?

**Comment by mukeshsoni** [comment]
@marksboyce I don't have to bandwidth to look at the mobile issues. Can you please help contribute?

**Comment by mukeshsoni** [comment]
I am closing this one since i can't find the time to work on mobile issues. Anyone kind enough to to send a PR can reopen it
