### ISSUE TITLE
Update package on ES6 syntax

### ISSUE THREAD

**Issue by Pave91** [mukeshsoni/react-telephone-input#119]
Warning: ReactTelephoneInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead.

**Comment by mukeshsoni** [comment]
@Pave91 Will add to list of next release. Thanks!

**Comment by mattgi** [comment]
related to React upgrade will be, `Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by mattgi** [comment]
@mukeshsoni do you have an ETA on the next release? Thanks.

**Comment by mukeshsoni** [comment]
I was trying to change the build and publish process some time back and I want to finish that before making the next release.

I will try and make a release in the next 2 weeks. Fingers crossed.

**Comment by mattgi** [comment]
Awesome, thanks for the update. appreciated.

**Comment by newswim** [comment]
Let me know if I can help with anything! This package fits perfectly with a project I'm doing at work.

**Comment by mukeshsoni** [comment]
@newswim Thanks for the offer! You can try and take a lot into any of the open issues and send me a PR

**Comment by mukeshsoni** [comment]
The lasest version has taken care of the deprecation warnings.
