### ISSUE TITLE
bug? classNames dose not transfer classNames to input

### ISSUE THREAD

**Issue by Nopzen** [mukeshsoni/react-telephone-input#120]
Hello Dev Team,

Is it intentional that the `classNames` prop *don't* put the given `classNames` to the `<input>` field rather than the `<div>` element that wraps the `<input>`.

In my case this conflicts with me setting error on the `<input>` field, and i would just like to know if this a bug or reality?

**Comment by mukeshsoni** [comment]
We set a class named `invalid-number` on the input box when the input is invalid. You can write a css rule for that selector.

**Comment by Nopzen** [comment]
Okay, cool beans :)

**Comment by omrihq** [comment]
Is the only way to style input is to style invalid-number?

**Comment by mukeshsoni** [comment]
There can be various ways you can do it in css. You can even use the container class and then get hold of the input element using css rule - 

.container_class input.invalid-number {
  /* your styling *
}
