### ISSUE TITLE
npm start doesnt work 

### ISSUE THREAD

**Issue by dorinaaaaalin** [mukeshsoni/react-telephone-input#123]
$ npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "c:\\node-v6.10.3-win-x64\\node.exe" "c:\\node-v6.10.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Sites\react-telephone-input\npm-debug.log

Someone pls help!

**Comment by mukeshsoni** [comment]
@dorinaaaaalin did you find out what the problem was?
