### ISSUE TITLE
onlyCountries doesn't work.

### ISSUE THREAD

**Issue by chrisbrooks** [mukeshsoni/react-telephone-input#128]
Hi, Trying to add the onlyCountries using the below but this doesn't work and just adds undefined in the list. Have attached screen shot.

<PhoneInput
      initialValue={defaultNumber}
      defaultCountry={defaultCountry}
      preferredCountries={preferredCountries}
      onlyCountries={['au', 'nz']}
      flagsImagePath={flagsImagePath}
      classNames={classNames}
      onChange={country => input.onChange(country.replace(/(\D)/g, ''))}
      onBlur={country => input.onBlur(country.replace(/(\D)/g, ''))} />

https://user-images.githubusercontent.com/5603144/27615473-ce95ca5a-5beb-11e7-80c8-a8f3b3e7c1d5.png

**Comment by mukeshsoni** [comment]
allCountries takes an array of objects. Look at `allCountries` structure in this file https://github.com/mukeshsoni/country-telephone-data/blob/master/country_telephone_data.js

**Comment by ateyssandier** [comment]
There's currently a todo to fix this.

https://github.com/mukeshsoni/react-telephone-input/blob/master/lib/ReactTelephoneInput.js#L3

I'm working on a fix for this currently.

**Comment by ateyssandier** [comment]
Added a PR for this, up to @mukeshsoni  to merge. I no longer need this fix so I will not be tracking this issue. https://github.com/ateyssandier/react-telephone-input/pull/1

**Comment by chrisbrooks** [comment]
Hi, I have updated to use an array of arrays like in your example @mukeshsoni but this still doesn't work. onlyCountries={[['au'], ['nz']]}. Is this still incorrect? Thanks

**Comment by mukeshsoni** [comment]
I did not say it's an array of arrays. I said you can get the structure here https://github.com/mukeshsoni/country-telephone-data/blob/master/country_telephone_data.js

**Comment by MitchEnfield** [comment]
I believe I've got it working.  An example would be:
```
<ReactTelInput
                defaultCountry='us'
                value={fields.phone}
                onChange={onPhoneChange}
                onlyCountries={[
                  {name: "United States", iso2: "us", dialCode: "1", priority: 0, format: "+. (...) ...-...."},
                  {name: "Canada", iso2: "ca", dialCode: "1", priority: 1, format: "+. (...) ...-....", hasAreaCodes: true},
                  {name: "Mexico (México)", iso2: "mx", dialCode: "52", priority: 0, format: "+..-..-..-...."},
                  {name: "Brazil (Brasil)", iso2: "br", dialCode: "55", priority: 0, format: "+..-..-....-...."},
                ]}
 />
```

**Comment by mukeshsoni** [comment]
Glad you figured it out. Closing the issue.

**Comment by bnjmn-jns** [comment]
the documentation states:
> you can pass an array of country iso2 names to be shown 

Annoying to have to dig through the closed issues to find out the correct syntax :/

**Comment by mukeshsoni** [comment]
@bnjmn-jns Why don't you submit a pull request to fix the documentation?

**Comment by bnjmn-jns** [comment]
Indeed. 
Perhaps a better fix would be to allow users to either pass an array of country iso2 codes (given that this data is already in the package, seems unnecessary to require a dev to look it up manually) _or_ specify the data explicitly (syntax it has now).
I'll take a look at that myself in the next few days
