### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by newswim** [mukeshsoni/react-telephone-input#132]
Hey @mukeshsoni,

Looks like the last few releases fixed the deprecation warnings that people on React > v15 have been getting. Do you have some time to create a new release? I don't see it breaking anything.

**Comment by mukeshsoni** [comment]
yeah, I just wish there were exhaustive tests. I am away from this project for such long periods of time that I forget what to test manually before each release. Will try to cut a minor release tomorrow.

**Comment by newswim** [comment]
That would be great. Thank you :-)

**Comment by mukeshsoni** [comment]
I have cut a new release 4.1.1. Check it out.

**Comment by newswim** [comment]
Works great! I only had to update one snapshot test, and the deprecation warning is gone. Thank you!!! 🍰 🍰
