### ISSUE TITLE
Country code gets appended one after another.

### ISSUE THREAD

**Issue by ktusharprdxn** [mukeshsoni/react-telephone-input#133]
When we select country code from dropdown, it is getting appended one after another. You can simply replicate this issue here http://unstack.in/react-telephone-input/

**Comment by mukeshsoni** [comment]
The link you have given has a very old version of the component. I am yet to update it. Please try it in your local environment or give me a link which has the latest component.

**Comment by ktusharprdxn** [comment]
@mukeshsoni I am able to replicate this issue on my local setup, here are the steps to replicate this issue:
click on U.S. vergins island and then click on another country it will get appended because when we have 4 digit country code it is displaying as +1 (169. 

Let me know if you have any queries. Thanks

**Comment by mukeshsoni** [comment]
Can you please point me to a repository which i can clone and try out?

**Comment by ktusharprdxn** [comment]
@mukeshsoni I can't share code due to some reasons.

**Comment by mukeshsoni** [comment]
give me a video or a gif at the least

**Comment by ktusharprdxn** [comment]
@mukeshsoni here is a video reference: https://drive.google.com/open?id=0B8zNahpyqyKoTEZrTmtXNDBobTA

**Comment by ktusharprdxn** [comment]
@mukeshsoni Did you reviewed video?

**Comment by mukeshsoni** [comment]
No, don't have the time. PRs are welcome.

**Comment by ktusharprdxn** [comment]
@mukeshsoni Can you please provide the steps that how would you expect PR from contributers? As I have seen there is no npm start command there in package.json I can't start server and make changes due to this.

**Comment by mukeshsoni** [comment]
@ktusharprdxn i am planning to use [nwb](https://github.com/insin/nwb) for the complete setup

**Comment by mukeshsoni** [comment]
@ktusharprdxn I have added back support for `npm start`. It will now start a server on `localhost:3000` and you can test all changes to src/ReactTelephoneInput.js there.

**Comment by mukeshsoni** [comment]
@ktusharprdxn Have fixed it in 4.3.4
