### ISSUE TITLE
Css is not working making it look ugly

### ISSUE THREAD

**Issue by Marcsimm** [mukeshsoni/react-telephone-input#134]
I npm insatlled the package and applied to a component like this 

```
import React from 'react';
import ReactTelephoneInput from 'react-telephone-input';

export default function PhoneInput() {
  return (
    <ReactTelephoneInput
      defaultCountry="se"
      flagsImagePath="./flags.png"
    />
  );
}

```

but when i test it in the browser and look in the element the css is not there.

**Comment by mukeshsoni** [comment]
You need to import 'react-telephone-input/withStyles'

**Comment by NickFranceschina** [comment]
FYI: it's actually `react-telephone-input/withStyles`

**Comment by mukeshsoni** [comment]
Thanks @NickFranceschina . That's the correct path @Marcsimm

**Comment by Marcsimm** [comment]
That fixes it thanks.
