### ISSUE TITLE
dropdown button of countries dosen't work!!

### ISSUE THREAD

**Issue by abdelwahebmoalla** [mukeshsoni/react-telephone-input#135]
Here is my code it might be my mistake i am still new to react

import { ReactTelephoneInput } from "react-telephone-input/lib/withStyles";

Inside render

<ReactTelephoneInput defaultCountry="us" flagsImagePath='../img/flags.png' 
                    onChange={this.handleInputChange} onBlur={this.handleInputBlur}
                    />

I used the image you told us to use.

**Comment by mukeshsoni** [comment]
You don't need the brackets for the import

```
import ReactTelephoneInput from "react-telephone-input/lib/withStyles"
```

**Comment by abdelwahebmoalla** [comment]
still same problem
this my code inside render
<ReactTelephoneInput defaultCountry="us" flagsImagePath="../img/flags.png" 
                    onChange={this.handleInputChange} onBlur={this.handleInputBlur}
                    />

**Comment by abdelwahebmoalla** [comment]
ReactTelephoneInput defaultCountry="us" flagsImagePath="../img/flags.png" 
                    onChange={this.handleInputChange} onBlur={this.handleInputBlur}

**Comment by abdelwahebmoalla** [comment]
i am sure of the path of the image

**Comment by mukeshsoni** [comment]
What was the problem? Can I get the error you get?

**Comment by abdelwahebmoalla** [comment]
ReactTelephoneInput.js:148 GET http://localhost:5000/img/flags.png 404 (Not Found)

**Comment by mukeshsoni** [comment]
Did you copy the image to `img` folder in your root?

**Comment by mukeshsoni** [comment]
You are making me debug a problem you have with your server setup. I advice you to take it to stackoverflow.
