### ISSUE TITLE
Sometimes there is a missing bracket by the number e.g U.S virgin Islands

### ISSUE THREAD

**Issue by NolizweGetMyBoat** [mukeshsoni/react-telephone-input#142]
Please see screen shot below
![screen shot 2017-08-10 at 12 01 13](https://user-images.githubusercontent.com/23026458/29165632-a9685bcc-7dc3-11e7-83e1-789eb05a5e1a.png)

**Comment by alexalghisi** [comment]
Also after selectin US Virgin Islands if you select another country the phone number displayed will be wrong.

**Comment by mukeshsoni** [comment]
@alexalghisi You need to create a separate issue to track that.

**Comment by mukeshsoni** [comment]
@NolizweGetMyBoat What missing bracket are you talking about? It's not clear from the screen shot. Can you please give more details and if possible, a gif or something.

**Comment by mukeshsoni** [comment]
@NolizweGetMyBoat I got what you meant. I can't fix that since fixing that would mean user cannot delete the number using backspace when cursor is at ')' since the component would again format it back to ')'. This number would anyways be formatted once the user starts typing in the whole number.

**Comment by mukeshsoni** [comment]
@alexalghisi I have fixed that bug where selected US Virgin islands from dropdown would completely mess the whole telephone number. It's there is version 4.3.3
