### ISSUE TITLE
Not compatible with React 16

### ISSUE THREAD

**Issue by frazboyz** [mukeshsoni/react-telephone-input#143]
In React 16, they have removed React.createClass which breaks this library.

**Comment by Si1kIfY** [comment]
Related to my issue #136

**Comment by satishnath** [comment]
I see that react-onclickoutside dependency has to updated, the newer version of the library have the necessary updates to make it React (16) complaint.

**Comment by mukeshsoni** [comment]
@frazboyz @Si1kIfY @satishnath I have updated the `react-onclickoutside` library to latest in v4.2.2.

**Comment by mukeshsoni** [comment]
Duplicate of #136

**Comment by satishnath** [comment]
Thank you so much for the library!
