### ISSUE TITLE
Click event propagating through flag div.

### ISSUE THREAD

**Issue by frazboyz** [mukeshsoni/react-telephone-input#144]
I had this issue where the country list appeared for a tenth of a second(roughly) and then disappeared. This was caused by the event propagating through the flag button and then clicking the input as well(Which hides the drop down).

The second line in this code block fixes the issue.

`
handleFlagDropdownClick(event) {
    event.preventDefault();
`

**Comment by mukeshsoni** [comment]
@frazboyz Thanks. Have added that piece of code in v4.2.3
