### ISSUE TITLE
autoFormat=false still formats input

### ISSUE THREAD

**Issue by trbarrett** [mukeshsoni/react-telephone-input#146]
Hi there,

I stumbled onto this component while looking for a react replacement of the intl-tel-input jquery plugin.

I've set `autoFormat` to `false`, but it seems to be formatting the input in some way. It's not possible for users to input their own spaces, dashes etc.

Is there a way I can let users type in whatever non-digit formatting they want?

**Comment by mukeshsoni** [comment]
@trbarrett The library only allows number input. `autoFormat={false}` will turn of formatting it does by putting the dashes etc as per the country convention.
