### ISSUE TITLE
add Name attribute

### ISSUE THREAD

**Issue by GhaithZamrik** [mukeshsoni/react-telephone-input#147]
I have a complex form in my project and am implementing react-telephone-input as an enhancement to the project, I am already using the name attribute to do lots of stuff already. 
is there a possibility to add a name attribute to the library?
am guessing it should be fairly simple

**Comment by mukeshsoni** [comment]
I don't understand what you are trying to say. There are no examples, no code samples, nothing.

**Comment by GhaithZamrik** [comment]
can the name attribute be added to as well so we could do something like this? 
```<ReactTelephoneInput
                    name={this.props.name}
                    value={this.state.num}
                    flagsImagePath="/images/flags.png"
                    onChange={this.handleInputChange}
                    onBlur={this.handleInputBlur}
                />```

**Comment by mukeshsoni** [comment]
What is the purpose of the name attribute?

**Comment by GhaithZamrik** [comment]
am using the name attribute in the input tag to do some validation and updating the backend 
```
    handleChange (e) {
        const value = e.target.checked ? e.target.checked : e.target.value;
        this.validateForm();
        this.setData(e.target.name, value);
    },
    setData (key, value = null) {
        if (!key) {
            throw new Error(`Key (${key}) missing from setData call`);
        }

        let newStateData = null;

        if (typeof(key) === 'object') {
            newStateData = _merge({}, this.state.data, key);
        } else {
            const keyArray = key.split('.');
            let deepKey = value;

            for (let i = keyArray.length - 1; i >= 0; i--) {
                deepKey = {
                    [keyArray[i]]: deepKey
                };
            }
            newStateData = _merge({}, this.state.data, deepKey);
        }


        this.setState({
            data: newStateData
        });

        return newStateData;
    },
```

**Comment by mukeshsoni** [comment]
Sorry, that's a very specific requirement for your use case. It doesn't add anything to the core working of the component.

**Comment by GhaithZamrik** [comment]
true, but it would still be useful when using multiple phone fields on the same form.

**Comment by mukeshsoni** [comment]
how so? you will anyways hookup the onChange event of each phone field with a separate event handler (or with handlers bound to some id using `this.handlePhoneChange.bind(this, id)`.

**Comment by GhaithZamrik** [comment]
okay, I need to validate each field and then the form itself as a whole, is there a way you suggest to reference the specific ReactPhoneInput field since i can't have a name nor an id?

**Comment by mukeshsoni** [comment]
Whenever anything changes in ReactTelInput, your onChange event handler is called. You can store those values in your state - 

```
<ReactTelephoneInput
        defaultCountry='in'
        flagsImagePath='/path/to/images/flags.png'
        onChange={this.handleInputChange.bind(this, 'rti-1')}
        />
<ReactTelephoneInput
        defaultCountry='in'
        flagsImagePath='/path/to/images/flags.png'
        onChange={this.handleInputChange.bind(this, 'rti-2')}
        />
```

And in your `handleInputChange` event handler - 

```
handleInputChange(name, newValue) {
    this.setState({
        form: {
            [name]: newValue
        }
    })
}
```

**Comment by GhaithZamrik** [comment]
thanks
