### ISSUE TITLE
problem with version 4.0.1 

### ISSUE THREAD

**Issue by Clcll** [mukeshsoni/react-telephone-input#150]
Hi!
I have same problem as described here https://github.com/mukeshsoni/react-telephone-input/pull/104. 
I tried to install  version 4.0.1 without  memoization but the version isn't valid 
Thx

**Comment by mukeshsoni** [comment]
You can install the latest version - 4.2.3 @Clcll

**Comment by Clcll** [comment]
@mukeshsoni thx for response. I am using 4.2.3 as you mentioned, it didn't resolve my problem
