### ISSUE TITLE
Add support for the readOnly property

### ISSUE THREAD

**Issue by goskydive** [mukeshsoni/react-telephone-input#151]
It would great to have support for the readOnly property on INPUT.

e.g. add... 
`readOnly: this.props.readOnly`
around line 758 of ReactTelephoneInput.js

**Comment by mukeshsoni** [comment]
@goskydive  That's a good suggestion. Better yet, there can be a `inputProps` prop which will be passed down to `input` element.

**Comment by goskydive** [comment]
@mukeshsoni Yes, I'd be super-happy with either of those.  Great component BTW.

**Comment by mukeshsoni** [comment]
In version 4.3.3

@goskydive I have added a prop named `inputProps` which sets any numbers of properties on the input element. E.g. 

```
<ReactTelephoneInput
  inputProps={{readOnly: true}}
  ...
/>
```
