### ISSUE TITLE
Hide sign plus (+)

### ISSUE THREAD

**Issue by saadaouad** [mukeshsoni/react-telephone-input#153]
Hello, 

Thanks for the great tool,
I need to hide the initial value `sign (+)` from the input.

**This my code**
```
 <Phone
    classNames={`ltr dib mr4 ${containerClass}`}
    defaultCountry="MA"
    flagsImagePath={flags}
    {...input}
 />
```

**Screen**
![image](https://user-images.githubusercontent.com/17694380/32253617-c93b75fe-be93-11e7-9b61-963999e491c8.png)

**Comment by mukeshsoni** [comment]
@saadaouad Rigth now, there's no way to do that. Suggestions on the best way to do it and PRs are welcome.

**Comment by saadaouad** [comment]
@mukeshsoni is there any update on this please?

**Comment by saadaouad** [comment]
@mukeshsoni Could you please reopen this issue and give us some insights to fix it

**Comment by mukeshsoni** [comment]
There's no way to do it right now and i don't have the time to think of a solution for it. You can raise a PR if you think of a solution. I will close this one since it's not a bug and not high on list of priorities.

**Comment by mukeshsoni** [comment]
@saadaouad You opened this issue in 2017. How did you take care of that requirement in the 2 years since then and now?

**Comment by saadaouad** [comment]
> You can raise a PR if you think of a solution. I will close this one since it's not a bug and not high on list of priorities.

Can you reopen this to keep trace for that?

**Comment by mukeshsoni** [comment]
Sorry, i don't have the bandwidth and don't think i will take it up any time soon.
