### ISSUE TITLE
Unformatted Number from the input 

### ISSUE THREAD

**Issue by anuragb26** [mukeshsoni/react-telephone-input#155]
Currently the onChange Handler provides number in the format valid for the country chosen.
Example : For India , the format is +.. .....-....." and I get the number in this format.
But How do  I get only the numbers being inputted without the country specific formatting ??

**Comment by mukeshsoni** [comment]
number.replace(/\D/G, '')

**Comment by mukeshsoni** [comment]
number.replace(/\D/g, '')

**Comment by anuragb26** [comment]
Thanks !
