### ISSUE TITLE
Localize the country name

### ISSUE THREAD

**Issue by cptdesro** [mukeshsoni/react-telephone-input#156]
It would be nice if there would be a props to override the country name, to localise it with the language we want. We could pass a json with the french names with the key of the country.

We love your component but we are developing a software in French, so we need to override countries name.

Thank you

**Comment by mukeshsoni** [comment]
@cptdesro 
You can do that using the `onlyCountries` prop. From the package `country-telephone-data`, pick `allCountries`, modify them as you like and send to ReactTelephoneInput as `onlyCountries` prop.

```
var ReactTelInput = require('react-telephone-input')
var countryTelData = require('country-telephone-data')
var localizedCountryData = localizeCountryNames(countryTelData.allCountries)

<ReactTelInput
    onlyCountries={localizedCountryData}
    ...otherProps
/>
```

Try it and let me know if it works.

**Comment by cptdesro** [comment]
Perfect Thanks, if you are interested, i can give you the list of localized country in french. It was long to localize each country.

**Comment by mukeshsoni** [comment]
You can put it on github and put a link here. I would be happy to add the data link to README section.
