### ISSUE TITLE
Less complains that flag.png is missing

### ISSUE THREAD

**Issue by KyleAMathews** [mukeshsoni/react-telephone-input#16]
I copied the `flags.png` file from the `examples/src` folder to the `/less` folder which solved things. Is this what it should be by default? I don't use Less so unsure.

**Comment by KyleAMathews** [comment]
also, related is that the relative path for the image gets compiled to `background: url([object Object])`. Apparently a known problem within Less. Changing that to an absolute path fixes things.

**Comment by mukeshsoni** [comment]
but how to know the absolute path? best would injecting the path at runtime through a prop and have a default value for the prop.

Can then set the background using DOM methods in componentDidMount. What do you think?

**Comment by mukeshsoni** [comment]
which compiler compiles the url string to [object object]? seems to work ok with lessify transform for browserify which we are using to compile example.less to example.css

**Comment by KyleAMathews** [comment]
Yeah, I like turning the path into a prop and taking it out of Less.

I'm using Webpack and its `less-loader`. Underneath it's using v. 2.5.1 of Less which is the latest. Not sure why it's happening.

**Comment by mukeshsoni** [comment]
have pushed the setting of background-image to flag style inside the component using prop - `fileImagePath`.

I wish i could remove the whole less and apply inline styles using javascript objects only.
