### ISSUE TITLE
Language in titles

### ISSUE THREAD

**Issue by erselnordlys** [mukeshsoni/react-telephone-input#160]
Hello!
I have an issue with changing language of countries from English to any others (Russian, in my case). Is there in option to set another language in titles list?

**Comment by mukeshsoni** [comment]
@erselnordlys There is no localization support. But you can pass the countries yourselves as a prop - `onlyCountries`

You can localize the list yourself by requiring it from the package [country-telephone-data](https://www.npmjs.com/package/country-telephone-data)

```
var ReactTelInput = require('react-telephone-input');
var countryTelData = require('country-telephone-data')
var onlyCountries = countryTelData.allCountries.map(localizeCountryNames)

// in your jsx
<ReactTelInput
    {...otherPropsForReactTelInput}
    onlyCountries={onlyCountries}
        />
```
