### ISSUE TITLE
Inferno error

### ISSUE THREAD

**Issue by frankPairs** [mukeshsoni/react-telephone-input#161]
Hi community!

I have a problem when I try to compact code with inferno using this component.

Seems that there is any incompatibility a error is produced only in compiled version (using  inferno):

Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.

I'm sure that is this component because I've tried to remove it and application works correctly. I'm going to investigate why it's happening, but if there is anyone with the same problem, please tell me.

Thanks!

**Comment by mukeshsoni** [comment]
I do not know what is Inferno or how it works. Let me know if you can figure out the root cause. I will be glad to help after that.

**Comment by frankPairs** [comment]
@mukeshsoni inferno is a library to reduce your bundle size. It's compatible with react functionalities and its size is only 9kb (https://github.com/infernojs/inferno).

Seems that there is anything in this library that doesn't work when you use inferno.

I tell you anything if I would discover the issue.

Thanks.

**Comment by mukeshsoni** [comment]
I have no idea about inferno. Please send across a pull request if you are able to find a solution
