### ISSUE TITLE
Minor flag rendering issue on some zoom levels

### ISSUE THREAD

**Issue by Kaarel94** [mukeshsoni/react-telephone-input#164]
On some zoom levels in the browser (seen in chrome unsure about other browser) edges of the adjacent flags from the flags.png can be seen. 

![image](https://user-images.githubusercontent.com/9853643/34986163-33880cda-fabf-11e7-84a5-9cfee8dd7e3b.png)

**Comment by mukeshsoni** [comment]
I was not able to reproduce this one. Please reopen in case you still see the issue.
