### ISSUE TITLE
Problem with Puerto Rican numbers format

### ISSUE THREAD

**Issue by aaronvine** [mukeshsoni/react-telephone-input#165]
Hi, there seems to be an issue with puerto rican phone numbers.

For example, if you type +17874104015, the formatting doesn't seem to work:

![2018-01-31_1043](https://user-images.githubusercontent.com/10596462/35613068-95634356-0673-11e8-8cdb-7a737ca476b6.png)

Thanks!

**Comment by mukeshsoni** [comment]
This PR for country-telephone-data should fix it - https://github.com/mukeshsoni/country-telephone-data/pull/7

I have released 0.5.5 for country-telephone-data

**Comment by mukeshsoni** [comment]
Oops, you are the one who made the PR :D
