### ISSUE TITLE
lodash version locked

### ISSUE THREAD

**Issue by RKushnir** [mukeshsoni/react-telephone-input#168]
I'm wondering if it's intentional that lodash dependency version is locked to "4.17.4". Looks like a typo to me. But if not, it would be good to know the reason. The [commit](https://github.com/mukeshsoni/react-telephone-input/commit/e818981057cc7872dd84e8adc74c4e37e3fc47e0) that introduced the change provides no explanation.

**Comment by mukeshsoni** [comment]
@RKushnir  I have completely removed the lodash dependency in v4.5.5

**Comment by RKushnir** [comment]
@mukeshsoni Thank you, awesome 🙂
