### ISSUE TITLE
onChange invoked in componentDidMount

### ISSUE THREAD

**Issue by mklishevych** [mukeshsoni/react-telephone-input#169]
Is there a reason why it's implemented this way? It doesn't make much sense to me, because there is no real change happening, component is just being mounted. And it also makes it harder to use, I have to make a flag to know that if onChange is being called for the first time, then it's not from the user input, but from the component being mounted.

**Comment by mukeshsoni** [comment]
I have completely forgotten why the `onChange` is called in `componentDidMount`. There must have been a reason but i did not document it.

I will try to test it without the `onChange` call and then remove it if it's unnecessary.

Thanks for reporting @mklishevych

**Comment by mukeshsoni** [comment]
@mklishevych I have published v4.4.4 removing the onChange call in componentDidMount. I think the call was there since it gives you back the formatted number. But i guess they can use the `getNumber` instance method to get the formatted number whenever they want

**Comment by mklishevych** [comment]
Thank you!

**Comment by lrojas94** [comment]
@mukeshsoni Found myself needing the guessed country, but since no `onChange` is called at first, no way to get the guessed country here. I see you talk about an instance method and whatnot here, is that possible?

**Comment by mukeshsoni** [comment]
You can add a ref on ReactTelephoneInput to get hold of it's instance

```
<ReactTelephoneInput
  ref={rtiRef}
/>

rtiRef.getNumber()
```

**Comment by lrojas94** [comment]
@mukeshsoni I don't get any `getNumber` method from the ref. In fact, to access the instance methods I need to go like this:

`phoneInputRef.current?.__wrappedInstance.guessSelectedCountry(value)`

I don't suppose the `__wrappedInstance` value is intentional here, but it's the only way I can access the instance methods.

**Comment by mukeshsoni** [comment]
I missed the `current` part since it's how the new react refs work. I don't know about the `__wrappedInstance` part. If it's working for you, that's good, i guess.

**Comment by lrojas94** [comment]
I tested both with `current` and the old `this.ref = ref`, but none of those had the `getNumber` method available. I'll probably check this package during the weekend, maybe I can find out what's going on and export it.

**Comment by mukeshsoni** [comment]
You are right. It's no longer there. I might have removed it in some iteration. I don't remember. You can raise a PR to add it.
