### ISSUE TITLE
1.2.5 release doesn't include lib directory

### ISSUE THREAD

**Issue by KyleAMathews** [mukeshsoni/react-telephone-input#17]

**Comment by mukeshsoni** [comment]
fixed in 1.2.7

**Comment by KyleAMathews** [comment]
Thanks! Everything "just worked" when I installed 1.2.7 :)

**Comment by mukeshsoni** [comment]
Great! thanks for your all help!

Do you have any requirement for validating the input number using external library (like https://github.com/googlei18n/libphonenumber)?
