### ISSUE TITLE
Auto focus breaks the component

### ISSUE THREAD

**Issue by sondremare** [mukeshsoni/react-telephone-input#171]
**Expected behaviour**
Setting the input prop ```autoFocus``` to true, the input element should automatically be focused. And the caret should be positioned at the end of any initial value.

**Actual behaviour**
The input element is automatically focused, but the component throws an error due to ```fillDialCode``` trying to perform stuff before the reference is available. Also, the caret is positioned at the start of the input field.

**Reproducibility**
https://codesandbox.io/s/zwn0v61vxm

**Comment by mukeshsoni** [comment]
Thanks for reporting @sondremare. Will take a look. 

Sharing codesandbox link makes it so much faster and easier to understand what you mean!

**Comment by sondremare** [comment]
Cool, let me know if you need anything else from me

**Comment by mukeshsoni** [comment]
@sondremare  I tried reproducing the issue but could not do so in chrome and firefox. For some reason, it works differently on codesandbox 🤔

**Comment by mukeshsoni** [comment]
ah, i didn't give the initial value. So happens only when `initialValue` is provided

**Comment by mukeshsoni** [comment]
@sondremare I have fixed the error/exception scenario. The cursor moving to the start of the text is browser behavior.
