### ISSUE TITLE
Remove inline CSS for flag images

### ISSUE THREAD

**Issue by blindingstars** [mukeshsoni/react-telephone-input#173]
With `flagsImagePath` commented out and this package's CSS not imported, the following is still added to the markup:

`<div class="flag us" style="width: 16px; height: 11px; background-image:url("flags.png");">`

This makes retheming the flag icons more difficult, as inline CSS needs `!important` overrides. Anyone using a custom spritesheet or other non-default solution will need to override these values.

I suggest moving the `width` and `height` to `.flag` inside the `react-telephone-input` default CSS and only inlining the `background-image` path if `flagsImagePath` has been passed in.

**Comment by mukeshsoni** [comment]
Thansk for the suggestions! Have incorporated in v4.5.8
