### ISSUE TITLE
Duplicate key issues when using preferredCountries

### ISSUE THREAD

**Issue by blindingstars** [mukeshsoni/react-telephone-input#175]
I've set 2 preferred countries in my `<ReactTelInput>` and run into this error in my console for each one:

`Encountered two children with the same key, flag_no_us. Child keys must be unique; when two children share a key, only the first child will be used.`

`Encountered two children with the same key, flag_no_mx. Child keys must be unique; when two children share a key, only the first child will be used.`

Because of this, the countries only show up in the "preferred" section at the top, not again in the rest of the list.

Is there a way that preferred countries could be assigned their own keys? `data-flag-key` is using uniques:

![image](https://user-images.githubusercontent.com/6765732/38788969-4489b7ec-4176-11e8-915d-36225407c020.png)

**Comment by mukeshsoni** [comment]
Thanks for reporting. They should be actually having different keys. Will look into it.

**Comment by mukeshsoni** [comment]
@blindingstars I have fixed the key issue in v4.5.7. Please verify and let me know if it works.

**Comment by blindingstars** [comment]
@mukeshsoni Thanks so much! All fixed 👍
