### ISSUE TITLE
Releases and changelog

### ISSUE THREAD

**Issue by renarsvilnis** [mukeshsoni/react-telephone-input#179]
Hi,
it would great if there would be a `changelog.md` file or github release for each version that documents changes.

Using `npm version <major|minor|patch>` (similary with yarn) automaticly increments package.json version and also creates a git tag.

Workflow like this makes it easy and fault-proof:

```bash
# 1. Create new version (must have committed other files before related to version)
# Version: v4.71.11
npm version minor

# 2. Push/Publish changes
# Version: v4.72.0
git push
git push --tags
npm publish
```

Also noticed that [version on npm](https://www.npmjs.com/package/react-telephone-input) might have been incorrect for last release. As it went from `4.7.11` => `4.71.11`.

**Comment by mukeshsoni** [comment]
@renarsvilnis That is a very good idea. I do not actually know how exactly does it work. I write my changes in changelog.md and they are automatically shown in github for that tag?

**Comment by mukeshsoni** [comment]
I think along with `npm version` i need to use github releases - https://help.github.com/articles/creating-releases/

Coupled with  [semver](https://www.npmjs.com/package/semver, they should create a nice changelog with semantic release versions.

**Comment by renarsvilnis** [comment]
@mukeshsoni With `npm version` you first create a release locally, then push it to GitHub once in GitHub, use "Releases" and select the version you just pushed.

Also as a version is in progress, like a couple of commits did something, but there are other things in progress before a new version release, you can start creating a draft release before even creating the final release. So once it's ready, less work to go back and see what changed.

`changelog.md` is an ok option as well.

**Comment by mukeshsoni** [comment]
I will keep it open so that i know that i need to follow this process from the next release.

**Comment by renarsvilnis** [comment]
You can use the emojis listed in the article to enhance the releases. Make them more readable at a quick glance
https://github.com/slashsBin/styleguide-git-commit-message

**Comment by mukeshsoni** [comment]
Cool! Thanks for the link!

**Comment by mukeshsoni** [comment]
Used `npm version` for the current release. Also added a changelog file. Made a mistake while using `npm version` for the first version! Hopefully i get used to the workflow.
