### ISSUE TITLE
When switching between Canada and USA in the dropdown, the number one is appended every time

### ISSUE THREAD

**Issue by NikkiMeganMoore** [mukeshsoni/react-telephone-input#180]
When you switch from CA to US or from US to CA, it adds a 1 every time instead of just staying the same.

Please consider fixing this issue, thank you!

**Comment by NikkiMeganMoore** [comment]
Is there any update on this issue? TIA

**Comment by villamil** [comment]
I just did a pull request to solve this issue

**Comment by mukeshsoni** [comment]
Have been fixed in 4.73.0 (sorry for the messy versioning. still learning semver), thanks to @villamil PR
