### ISSUE TITLE
No onKeyDown event. Impossible to track a TAB press

### ISSUE THREAD

**Issue by EugeneKovalev** [mukeshsoni/react-telephone-input#181]
I have to save a phone value on TabPress but i couldn't find any mean of doing this. There's no onKeyDown event in the lib. Maybe I'm doing smth wrong.

Any help is highly appreciated!

**Comment by mukeshsoni** [comment]
There is `inputProps` prop, but if you use it to pass a onKeyDown event handler, things will break in the component. I will probably need to make changes so that i can merge eventHandlers on input passed as prop as well as the ones internal to the component.

**Comment by mukeshsoni** [comment]
@EugeneKovalev I was able to do what you asked for using `inputProps`. Demo here https://codesandbox.io/s/ov8k9nk73q
