### ISSUE TITLE
not able to select Kazakhstan flag

### ISSUE THREAD

**Issue by Infinity1high** [mukeshsoni/react-telephone-input#182]
As Kazakhstan country code has value '+7'  , the same as Russian country code, it is not possible to select kazakhstan's flag.
Actually country code is +77

**Comment by mukeshsoni** [comment]
Will take a look. Thanks for reporting!

**Comment by mukeshsoni** [comment]
@Infinity1high I could not reproduce the error. Maybe fixed in 4.73.0
