### ISSUE TITLE
replaceCountryCode works incorrectly

### ISSUE THREAD

**Issue by olleolle** [mukeshsoni/react-telephone-input#183]
Enter a phone number `+55-55-55`
Choose USA `+1 (555) 5`
Choose Canada `+1 (155) 55`
Choose USA `+1 (115) 555`

**Comment by mukeshsoni** [comment]
Fixed in 4.73.0, thanks to Villamil's PR https://github.com/mukeshsoni/react-telephone-input/pull/185
