### ISSUE TITLE
mask is not working properly

### ISSUE THREAD

**Issue by ahmetkuslular** [mukeshsoni/react-telephone-input#186]
<img width="855" alt="screen shot 2018-09-05 at 16 50 14" src="https://user-images.githubusercontent.com/17436691/45097530-bd279c80-b12b-11e8-940d-4aa1642ad0c5.png">

Mask length accepts a large phone number entry!

**Comment by mukeshsoni** [comment]
@ahmetkuslular What is mask length? Is it a `<input>` element attribute?
