### ISSUE TITLE
Component is not accessible

### ISSUE THREAD

**Issue by Nazin** [mukeshsoni/react-telephone-input#187]
When there are multiple text inputs on the page and react-telephone-input is one of them, user cannot correctly navigate using only keyboard.

Pressing `tab` before the react-telephone-input will correctly focus the phone field. Next `tab` will focus on flag element, but there is no indicator that the flag element is focused nor user is able to select the flag using keyboard only.

**Comment by mukeshsoni** [comment]
Yup, that's a problem with this component. I never thought about accessibility while building it. I don't know a easy way to put in keyboard navigation in the current code. Specially one related to navigating countries in the list and selecting one. 

I am thinking about rewriting the whole thing to only support react 16+.

**Comment by mukeshsoni** [comment]
@Nazin 
I have changed the flag element to a `button`, which means it can now be focused and activated using keyboard. I have also added manual down key activation for flag dropdown.

You can find these fixes in ver 4.73.1. Let me know if you find other accessibility issues.

**Comment by mukeshsoni** [comment]
@hlomzik Thanks for the input. Have published bugfix as a patch version - v4.73.2 with your suggested change. I didn't understand why it should be a minor version. If a minor version makes sense, i can cut another release with v4.74.0

**Comment by hlomzik** [comment]
@mukeshsoni Hmm, yes, if this will be done fully correct and transparent it looks like a patch, yes. But now there is still a version with button getting submit on npm, which breaks the forms a little. And I see a fixed version in `a11y` branch, just not on npm.
Thanks for changes!

**Comment by mukeshsoni** [comment]
Ah, it's not merged to master. But npm should have it. I published from the a11y branch.

**Comment by mukeshsoni** [comment]
@hlomzik @Nazin Wow, so sorry. Don't know why i though i had published v4.73.3 but never did. Have pushed the change with type='button' in v4.73.3.

**Comment by ksikora** [comment]
@mukeshsoni 

We tested your fix in 4.73.3 but it does not work correctly. Problem is `tabIndex="0"` for the container of button element for selected-flag. It results in additional tab click required, to focus flag.

What is more div with this tabIndex plays no role and has no attached keyboard action. It should be removed.

![image](https://user-images.githubusercontent.com/1908677/47358669-aa146000-d6ca-11e8-9357-a75c9fb48338.png)
