### ISSUE TITLE
Flags button shoould have type="button"

### ISSUE THREAD

**Issue by LeoGardel** [mukeshsoni/react-telephone-input#189]
When the flags are represented by a button and I press enter to submit the form, it is taking precedence over the true submit button, the one that has a type="submit".

To prevent that, I think that the button should have a type="button", or, at least, we should be able to pass custom props to the button in the same way we are able to do to the input.

**Comment by mukeshsoni** [comment]
@LeoGardel 
My bad. I thought i had published the fix around 10 days back but i think i forgot to publish :)

Have pushed the fix in v4.73.3
