### ISSUE TITLE
Blacklist one country

### ISSUE THREAD

**Issue by abumalick** [mukeshsoni/react-telephone-input#194]
Thanks for your component 👍 

We have a use case where we want to remove some country from the list. Would you accept a PR would implement this functionality ?

We could pass an array of country names to blacklist as a prop for example.

**Comment by mukeshsoni** [comment]
The feature is already there. There is a prop called `onlyCountries` which takes the list/array of countries to be shown in the dropdown. 

https://github.com/mukeshsoni/react-telephone-input#onlycountries

**Comment by abumalick** [comment]
I didn't want to include the full list of countries in my code.

But I think you are right, I think I can import the phone list from your package and pass it directly to the prop.

Right ?

Thank you very much
