### ISSUE TITLE
Component is still not accessible

### ISSUE THREAD

**Issue by Nazin** [mukeshsoni/react-telephone-input#195]
Component is still not fully accessible, please take a look at https://github.com/mukeshsoni/react-telephone-input/issues/187#issuecomment-432216241

> We tested your fix in 4.73.3 but it does not work correctly. Problem is tabIndex="0" for the container of button element for selected-flag. It results in additional tab click required, to focus flag.
> 
> What is more div with this tabIndex plays no role and has no attached keyboard action. It should be removed.

**Comment by mukeshsoni** [comment]
Please submit a Pull Request. I do not have the bandwidth work on the component right now.

Or fork.

**Comment by mukeshsoni** [comment]
version 4.74.4 fixes that
