### ISSUE TITLE
React in dependancies instead of peer dependancies

### ISSUE THREAD

**Issue by ingwet** [mukeshsoni/react-telephone-input#2]
Hey there!

Just came across this plugin that I absolutely love (thanks a lot for it), but it turns out to be breaking the code in a manner, very well described here http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined

Please alter the dependancies

**Comment by mukeshsoni** [comment]
Have made react and lodash peerDependencies
