### ISSUE TITLE
Can't load with webpack / babel setup

### ISSUE THREAD

**Issue by tydicefm** [mukeshsoni/react-telephone-input#20]
I have the current webpack setup:

```js
module.exports = {
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    entry : './src/client.js',
    output: {
        path      : require('path').resolve('./build/js/'),
        publicPath: '/public/js/',
        filename  : '[name].js'
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: 'style!css' },
            { test: /\.js$/, exclude: /node_modules/, loader: require.resolve('babel-loader') },
            { test: /\.json$/, loader: 'json-loader'},
            { test: /\.js$/, loader: 'eslint-loader', exclude: /node_modules/ },
            { test: /\.less$/, loader: 'style!css!less' }, // Added only to try to have support for LESS
        ]
    },
    stats: {
        colors: true
    },
    devtool  : 'source-map',
    watch    : true,
    keepalive: true,
    plugins  : [],
};
```

When I do `import ReactTelInput from 'react-telephone-input';` it crashes with the following error:

```sh
[..]/node_modules/react-telephone-input/less/default.less:1
(function (exports, require, module, __filename, __dirname) { .react-tel-input
                                                              ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([..]/node_modules/react-telephone-input/lib/index.js:28:1)
    at Module._compile (module.js:460:26)
```

Webpack / the Bable loader seem to try to include the `.less` file as a JS file. Is there a way of forcing it to be LESS? 

Manually commenting the `require('../less/default.less');` solves my issue for now as I can manually compile the LESS, but it obviously isn't ideal.

**Comment by mukeshsoni** [comment]
you can add an alias to your webpack config for the less file

**Comment by KyleAMathews** [comment]
You need to add `.less` to the `resolve.extensions` array :) had this exact problem too many times :)

**Comment by KATT** [comment]
And if you'd use `react-telephone-input` in babel on the server..? :)

**Comment by KyleAMathews** [comment]
Yes, this module should work just fine if you're server rendering your react site.

**Comment by KATT** [comment]
See https://github.com/KATT/react-telephone-input-issue

```sh
git clone git@github.com:KATT/react-telephone-input-issue.git
cd react-telephone-input-issue/
npm install
node index.js
```

:point_up_2: to reproduce crash. Is there a workaround for this?

**Comment by KyleAMathews** [comment]
Oh that. Yes, you can't require this directly into node as it doesn't "enhance" requires like Webpack and Browserify do. For Webpack projects, you need to compile projects to a UMD js file which you then require into node. This is unfortunately poorly documented atm. Perhaps the best documentation I know of atm is http://jxnblk.com/writing/posts/static-site-generation-with-react-and-webpack/

**Comment by KATT** [comment]
Or forking and removing the `require('../less/default.less');` line?
