### ISSUE TITLE
BrowserslistError since MaterialUi v4

### ISSUE THREAD

**Issue by ttridon** [mukeshsoni/react-telephone-input#200]
Hi,

Since I updated MaterialUI to v4.1.1, "react-telephone-input/lib/withStyles" dont work anymore.
It display an error:

Failed to compile.

./node_modules/react-telephone-input/css/default.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-telephone-input/css/default.css)
BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)

If I use I import "react-telephone-input", the component works, but the flags are not displayed.

Do you have the same issue since MaterialUi v4 ? 

Thx

**Comment by mukeshsoni** [comment]
> Maybe you are using old Browserslist or made typo in query.

Which query are you talking about? Can you point to the code?

**Comment by ttridon** [comment]
I'm using it in a React application.
I dont even use it, simply import it trigger the error:

> import ReactTelephoneInput from 'react-telephone-input/lib/withStyles';

**Comment by mukeshsoni** [comment]
The css doesn't have any such query. There's no reference to `android` in the css file.
