### ISSUE TITLE
Get value of the inputted number ?

### ISSUE THREAD

**Issue by mightwork** [mukeshsoni/react-telephone-input#22]
what is the easiest way to get the number inputted from the user ?

**Comment by mukeshsoni** [comment]
I didn't get it? For this component, the end user can type the number or copy paste.

If you mean the programmer using this component, you can pass in a value prop, `this.prop.value`, to give initial input.

**Comment by mightwork** [comment]
I need to get the value of the number inputted  at the time of making a post request .

**Comment by mukeshsoni** [comment]
you can send a function reference to onChange prop. `<ReactTelephoneInput onChange={yourCallback}>`. every time a change is made to the input field your callback will be called.
