### ISSUE TITLE
lessify is required

### ISSUE THREAD

**Issue by deepakjois** [mukeshsoni/react-telephone-input#25]
when I do `npm install react-telephone-input` on Node 4.0, and then try to use this component, I get

```
Cannot find module 'lessify' from '/…<snip>…/node_modules/react-telephone-input'
```

**Comment by mukeshsoni** [comment]
are you using npm 3.x for installing the module?

**Comment by deepakjois** [comment]
I am using npm 2.14.4, the default version that comes with Node 4.1.1

**Comment by deepakjois** [comment]
In any case, it would be nice not to depend on `lessify`. I would rather copy the static assets separately

**Comment by mukeshsoni** [comment]
> I would rather copy the static assets separately
That can be a separate discussion. 

For now, i cannot  think of a reason why it can't find lessify since it's there in dev dependencies. And i don't have node 4.* on my system. Will look at it once i can find some time.

**Comment by mukeshsoni** [comment]
@deepakjois and pull requests are welcome too :)

**Comment by mukeshsoni** [comment]
I have added the dist folder to npm folders. You can require from the generated file in dist folder and not need the less preprocessor.

**Comment by mukeshsoni** [comment]
@deepakjois Lessify is no longer required from 3.0.0 onwards. You can require a version of the library with the css by requiring require('react-telephone-input/lib/withStyles'). The default import will import the component without any styles.

**Comment by deepakjois** [comment]
On Mon, Apr 4, 2016 at 7:30 PM, Mukesh Soni <notifications@github.com>
wrote:

> @deepakjois <https://github.com/deepakjois> Lessify is no longer required
> from 3.0.0 onwards. You can require a version of the library with the css
> by requiring require('react-telephone-input/lib/withStyles'). The default
> import will import the component without any styles.
>
>
>
Thank you. I will try it out.

**Comment by Ral15** [comment]
I still get this problem, 

`Browserify Failed!: Cannot find module 'lessify'  from '/<myproject>/node_modules/react-telephone-input'`

**Comment by LennyBoyatzis** [comment]
Firstly, thanks @mukeshsoni for this component!

Secondly, +1 on this issue even with requiring 'react-telephone-input/lib/withStyles'. @mukeshsoni @deepakjois any thoughts?

**Comment by jooj123** [comment]
This is still an issue for me +1
Its because of the lessify transform in `package.json` - i think the transform should only be applied as part of the build process?

**Comment by mukeshsoni** [comment]
There is no direct dependency on `lessify` in the current release.
