### ISSUE TITLE
Enable support for autocomplete

### ISSUE THREAD

**Issue by deepakjois** [mukeshsoni/react-telephone-input#26]
Right now, the input field inside this component does not get autocompleted. One way to do it would be to add `autoComplete='tel'` as one of the attributes to the input tag

**Comment by mukeshsoni** [comment]
Did you try doing it? What is the expected behavior?

**Comment by deepakjois** [comment]
I am sorry, don’t understand your question exactly.

If you are asking if I have tried `autocomplete='tel'` on an input tag, then the answer is yes. I have tried it, and it works in Chrome and autocompletes the phone number that is set in your Chrome Autofill settings

**Comment by mukeshsoni** [comment]
Yup, that was the question. I will add the autocomplete thing

**Comment by mukeshsoni** [comment]
I have released a new version (1.3.2) which has this update.
