### ISSUE TITLE
Prefix componentWillReceiveProps with UNSAFE_

### ISSUE THREAD

**Issue by tomdohnal** [mukeshsoni/react-telephone-input#266]
As React throws a warning when you use the `componentWillReceiveProps` lifecycle method, we should either prefix it with the `UNSAFE_` keyword or refactor it to use a different approach. 

There are pending pull requests for both these approaches #265 #247 :)

**Comment by mukeshsoni** [comment]
Version `4.74.4` does not have `componentWillReceiveProps` any more.
