### ISSUE TITLE
How do you get value out of the module?

### ISSUE THREAD

**Issue by captDaylight** [mukeshsoni/react-telephone-input#27]
I've tried wrapping it in a form element, but onSubmit doesn't return any values. There don't seem to be any hooks for passing down a function to handle actions, how do you go about getting the value out?

**Comment by mukeshsoni** [comment]
Use the `onChange` prop. Pass a function reference to it and that function will be called on every change of value in the input box.

```
<ReactTelephoneInput onChange={(tel) => console.log('input no.: ', tel)) />
```

**Comment by captDaylight** [comment]
Awesome, thanks!

**Comment by anuragb26** [comment]
How do I get the unformatted number ?
