### ISSUE TITLE
Highlight index in drop down is always off by 1

### ISSUE THREAD

**Issue by johanneslumpe** [mukeshsoni/react-telephone-input#29]
When selecting a country from the dropdown, the next time the dropdown is opened the highlight index is off by 1.

Interestingly this does not happen on the demo...

**Comment by johanneslumpe** [comment]
Yeah not sure what happened here, closing as i cannot reproduce it anymore...

**Comment by johanneslumpe** [comment]
Ok, got to reproduce it:

Using the component with webpack, using `less-loader`. Just requiring the component and then bundling leads to a weird artifact in the drop down - an option with `undefined` as name. Not sure where it is coming from - any ideas?

**Comment by mukeshsoni** [comment]
Are you using the latest version from npm? This bug was fixed in an earlier version

**Comment by johanneslumpe** [comment]
@mukeshsoni yep, using `1.3.2`  from npm.

**Comment by mukeshsoni** [comment]
ok, looks like a issue. Am a little busy now. Will take a look as soon as i get some time.

**Comment by johanneslumpe** [comment]
Ok cool, thanks. I'm on a deadline here though, so if you tell me that this definitely is not fixable until Friday, then I will have to come up with something else.

**Comment by mukeshsoni** [comment]
Pull requests are also welcome.

**Comment by johanneslumpe** [comment]
Yes of course, but doesn't make sense here though since you said you previously fixed this issue. So you should have the fix ready I assume :)

**Comment by mukeshsoni** [comment]
Ah, but it looks like i didn't. Seems like a build issue but need to investigate.

**Comment by johanneslumpe** [comment]
@mukeshsoni It seems that the output is incorrectly transpiled.

It turned
```javascript
var countryDropDownList = map(this.state.preferredCountries.concat(this.props.onlyCountries), function(country, index) {
```
into
```javascript
var countryDropDownList = map([this.state.preferredCountries].concat(_toConsumableArray(this.props.onlyCountries)), function (country, index) {
```
Notice the square brackes around `this.state.preferredCountries`. That causes the index issue.

Since you are using `react-component-gulp-tasks` we should try to update to the latest version (only the patch version got bumped) and see if that fixes things :)

I will send a PR in a few minutes - would you be able to build a version with those updated dependencies and then cut a new release? That shouldn't take too long :)

**Comment by mukeshsoni** [comment]
sure, will do. thanks for the help.

**Comment by johanneslumpe** [comment]
Well let's see if this really fixes the issue :)

**Comment by mukeshsoni** [comment]
The problem line is surely fixed after the latest build -

From lib/index.js
```
map(this.state.preferredCountries.concat(this.props.onlyCountries), function (country, index) {
```

**Comment by johanneslumpe** [comment]
I just confirmed - works! Thanks @mukeshsoni :+1:
