### ISSUE TITLE
Setting `us` or `ca` as default country chooses incorrect country

### ISSUE THREAD

**Issue by gleuch** [mukeshsoni/react-telephone-input#293]
Passing `us` or `ca` as defaultCountry no longer chooses "United States" or "Canada" as the correct entry or flag image. Instead it defaults to "United States Minor Outlying Islands", which does not have a defined flag.

<img width="414" alt="Screen Shot 2020-03-27 at 16 44 32" src="https://user-images.githubusercontent.com/9039/77799101-71f51780-704a-11ea-9f19-b879bd73fa49.png">

Works in v4.74.4, broken in v4.75.4.

**Comment by mukeshsoni** [comment]
@gleuch Fixed in 4.75.5
