### ISSUE TITLE
incorrect country selection from drop down

### ISSUE THREAD

**Issue by vishal-techbitsolution** [mukeshsoni/react-telephone-input#309]
When I select any country from drop down and suppose there is any other with same country code then it picks the one which is at very end of list. E.g.
Aland Islands and finland has same country code +358, If I choose Aland Islands it will select finland because it is at very end of list

**Comment by carlos-soto** [comment]
@vishal-techbitsolution I was having the same issue, you can also reproduce this issue very easily with Canada, USA and United States Minor Outlying Islands
![react-telephone-input](https://user-images.githubusercontent.com/900934/80760713-94b99680-8af6-11ea-8010-44f2c4daa7cf.gif)
I downloaded the demo and it works fine, which is very strange. 
@mukeshsoni, any ideas?

**Comment by bulby97** [comment]
I had to implement my own countries list by removing unwanted duplicates.

**Comment by carlos-soto** [comment]
@bulby97, @vishal-techbitsolution downgrading to 4.74.4 worked for the Canada, USA and United States Minor Outlying Islands. It didn't work for Aland Islands though, my guess is that it has something to do with the character encoding, notice the "Å"
![react-telephone-input](https://user-images.githubusercontent.com/900934/80771150-bd9a5580-8b0f-11ea-9376-a564c019cac3.gif)

Also, strangely enough, an onFocus event that didn't propagate the event caused this behavior as well.

hope this helps @mukeshsoni, thank you so much for your awesome work!

**Comment by mukeshsoni** [comment]
@carlos-soto which version had the bug?

**Comment by mukeshsoni** [comment]
This is fixed in v4.75.5

**Comment by carlos-soto** [comment]
Hey @mukeshsoni, so sorry for the late response. I just updated to 4.75.5 and can validate that the library works correctly for the Aland Islands/Finland and the Canada/USA/United States Minor Outlying Islands cases.

![react-telephone-input](https://user-images.githubusercontent.com/900934/80999894-9a6af100-8e02-11ea-8056-5adfdddb1d49.gif)


Thank you so much for looking into this in such a timely manner!
