### ISSUE TITLE
how can i use this without npm?

### ISSUE THREAD

**Issue by towonzhou** [mukeshsoni/react-telephone-input#32]

**Comment by KyleAMathews** [comment]
Why?

**Comment by mukeshsoni** [comment]
You can take the js and css files from `dist` folder and also take the flags.png file from examples folder.

**Comment by towonzhou** [comment]
@KyleAMathews  i want use this on rails.

**Comment by towonzhou** [comment]
@mukeshsoni ok, thx

**Comment by KyleAMathews** [comment]
Managing your dependencies with NPM is really powerful. You might consider learning how. There's lots of tutorials on the internet on how to do this e.g. http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/

**Comment by towonzhou** [comment]
@KyleAMathews  it is a good way. I try this.

**Comment by towonzhou** [comment]
@KyleAMathews use this way. can i use material-ui with rails?

**Comment by KyleAMathews** [comment]
@towonzhou yup, and a huge list of other React components on NPM. https://react.parts/web

**Comment by towonzhou** [comment]
@KyleAMathews nice!
