### ISSUE TITLE
less-loader is required

### ISSUE THREAD

**Issue by nadav-dav** [mukeshsoni/react-telephone-input#34]
When running my webpack configuration, the build is failing over this line:
`require('../less/default.less');`
Since I do not have `less-loader` in my project, it does not know how to handle `.less` files.

What do you think will be the right solution to this? precompile the css? have it as an external file to include in the project?

I am curious to so learn your opinion about that. Thanks! :D

**Comment by mukeshsoni** [comment]
This is surely a problem with the output file, which assumes that you need to have a less loader in your build step. Will fix that when i have time.

In the meantime, you can add a less loader in your webpack config file like so -

```
loaders: [
            {
                test: /\.less$/,
                loader: 'style!css!less'
            },
// your other loaders
]
```
