### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by mordrax** [mukeshsoni/react-telephone-input#35]
This is a fast and compact component but it's missing a few important features such as:

- Can't tell from the callback if the number is valid or not, it just gives me a number.
- No way to pass a number into it via props, the state is defaulted to ''
- Would be nice to have a numbers only format without hyphens, spaces etc

**Comment by mukeshsoni** [comment]
> Can't tell from the callback if the number is valid or not, it just gives me a number
- good point. will try and get that in.

> No way to pass a number into it via props, the state is defaulted to ''
- is the 'value' prop not working for you?

> Would be nice to have a numbers only format without hyphens, spaces etc
- valid request again. will try and get that in.

**Comment by mordra** [comment]
My bad, had a look at the code and it looks fine. I didn't understand what getDefaultProps was doing.

**Comment by mukeshsoni** [comment]
I too had forgotten that the formatting can be turned off by using the prop `autoFormat: false`.

For checking on which props are supported, you can look at the propTypes object in the source file.

**Comment by mukeshsoni** [comment]
2 and 3 are already there. I just didn't realise it.

For (1), i.e. to check if a number is valid or not, you can directly call isNumberValid method on the component. E.g. usage - 

```
var RTI = require('react-telephone-input')

if(!RTI.isNumberValid(number)) {
    // do something
}
...
```

**Comment by hynese** [comment]
I can't get the validation to work...

```
handlePhoneChange(telNumber, selectedCountry) {
     console.log('input changed. number: ', telNumber, 'selected country: ', selectedCountry);

     //this fails:
     ReactTelephoneInput.isNumberValid(telNumber);   

     
  }
```


`Uncaught TypeError: _reactTelephoneInput2.default.isNumberValid is not a function`

**Comment by mukeshsoni** [comment]
@hynese Can you try `isValid`? 

```
ReactTelephoneInput.isValid(telNumber);  
```

**Comment by hynese** [comment]
I just did that:

`generated.js:31049 Uncaught TypeError: _reactTelephoneInput2.default.isNumberValid is not a function`

**Comment by hynese** [comment]
I'm still struggling with this...

I'm doing:

`import ReactTelephoneInput from 'react-telephone-input'`

And then I do:

```
handlePhoneChange(telNumber, selectedCountry) {
    console.log('input changed. number: ', telNumber, 'selected country: ', selectedCountry);
    ReactTelephoneInput.isValid(telNumber);
}
```

Yet all I see is this error:
```
Uncaught TypeError: _reactTelephoneInput2.default.isValid is not a function
    at Member_Account.handlePhoneChange
```

**Comment by mukeshsoni** [comment]
@hynese My mistake. It's actually set to the prop `isValid`. So, you can either pass a function reference to `isValid` prop to use your own validation function. If you don't have any, you can use the one we have in the component - 

```
var countryData = require('react-telephone-input/country_data.js')
var startsWith = require('lodash/string/startsWith');
var some = require('lodash/collection/some');

function isNumberValid(inputNumber) {
    var countries = countryData.allCountries;
    return some(countries, function(country) {
        return startsWith(inputNumber, country.dialCode) || startsWith(country.dialCode, inputNumber);
    });
}

and then use this `isNumberValid` function whereever you want it.
```

Should work. Let me know if it doesn't.

**Comment by hynese** [comment]
Does this mean it's only checking based on the number starting with the country code?

Why not check the phone number is valid according to the number mask?

```
Object{
    dialCode:"44",
    format:"+.. .... ......",
    iso2:"gb",
    name:"United Kingdom",
    ...
}
```

**Comment by omrihq** [comment]
Has this been addressed?

**Comment by mukeshsoni** [comment]
What has been addressed?
