### ISSUE TITLE
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node

### ISSUE THREAD

**Issue by sombro** [mukeshsoni/react-telephone-input#36]
![image](https://cloud.githubusercontent.com/assets/7949997/12326490/2bd96a8e-bae2-11e5-9818-30ca656f9640.png)

**Comment by mukeshsoni** [comment]
The component still has react dependency at >- 0.12.*. There is no plan to upgrade to 0.14.* unless those methods are actually removed in a react version.

**Comment by mukeshsoni** [comment]
fixed in 2.0.1 release

**Comment by sombro** [comment]
Thank you!
