### ISSUE TITLE
Incorrect manual input of number (if use cmd+A)

### ISSUE THREAD

**Issue by sombro** [mukeshsoni/react-telephone-input#38]
If cmd+A all text from input and then to try enter number "7918", you will receive "9718".
![vv 1](https://cloud.githubusercontent.com/assets/7949997/12394184/5d62350a-be0b-11e5-9ad1-ce49b56066d9.gif)

**Comment by jaredsohn** [comment]
I think this pull request fixes it: https://github.com/mukeshsoni/react-telephone-input/pull/51

However, there are still weird cursor problems when you try to edit a formatted phone number.

**Comment by mukeshsoni** [comment]
@jaredsohn  What are the weird cases?

**Comment by jaredsohn** [comment]
If you move the cursor to somewhere in the middle of the number and start typing, the cursor jumps to the end after the first character is entered.  (Fortunately, this situation shouldn't happen too often.)

**Comment by gdehmlow** [comment]
I'm encountering this problem as well

**Comment by jaredsohn** [comment]
A way to solve this would be to move validation to an onBlur event, at least when editing in the middle of the number.

**Comment by mukeshsoni** [comment]
Fixed in 3.6.2 with @jaredsohn's PR. Thanks @jaredsohn !
