### ISSUE TITLE
Can't choose countries with arrow-buttons

### ISSUE THREAD

**Issue by sombro** [mukeshsoni/react-telephone-input#39]
If I try to move in the list of countries using arrow-buttons , it doesn't work and console says: `Uncaught TypeError: Cannot read property 'setState' of undefined`

**Comment by mukeshsoni** [comment]
Shit! Thanks for reporting. Fixed in 2.0.4

**Comment by sombro** [comment]
Thank you! :)

Now works, but in console:
`rollbar.min.js:1 Uncaught TypeError: Cannot read property 'getElement' of undefined`

**Comment by mukeshsoni** [comment]
that error is from some other component (named rollbar, it seems)

**Comment by sombro** [comment]
No, such source is because all our application is compiled into one file. Don't watch at it.
This error occures just when use arrow-buttons in telephone-input

**Comment by mukeshsoni** [comment]
ooo, you are right. Can you check now? 

P.S. I need to start writing tests

**Comment by mukeshsoni** [comment]
2.0.7 is the version to try

**Comment by sombro** [comment]
Perfect now! *thubsup*
