### ISSUE TITLE
correct peer dependency of lodash

### ISSUE THREAD

**Issue by razagill** [mukeshsoni/react-telephone-input#4]
Hi,
Can you please update the lodash peer dependency to the latest, can't install it if your application has lodash ^3.6.0.

**Comment by mukeshsoni** [comment]
Need to test if it works with latest lodash (which has some breaking changes from the previous version). Did you try cloning the repo and changing lodash peerdependency version yourself? If yes, did it work?

**Comment by razagill** [comment]
Actually I started off with another repo with your code as base, changing everything to ES6 and react 0.13.2 now. Also it seems to works with the latest lodash but I have still other errors to solve though. Reason for doing so is I wanted to have some custom features and wanted them fast. Hope it's okay with you?

**Comment by mukeshsoni** [comment]
Of course. Let me know if the features make sense to everyone and the ES6 you have written can be transpiled to ES5 using babel. Might as well merge them.

**Comment by razagill** [comment]
Great, I've actually got it working with ES6 now and will be adding the features in the next couple of weeks. And to answer your question, you can safely update to the latest version of lodash it won't break anything.

**Comment by mukeshsoni** [comment]
Thanks. Will update.
