### ISSUE TITLE
Unable to resolve module ../less/default.less

### ISSUE THREAD

**Issue by Nemant** [mukeshsoni/react-telephone-input#41]
I did an npm install but when importing the module I get the following error:

"Unable to resolve module ../less/default.less from /Users/username/Dev/AwesomeProject/node_modules/react-telephone-input/lib/index.js: Invalid directory /Users/username/Dev/AwesomeProject/node_modules/react-telephone-input/less/default.less"

I checked and all the paths and files exist.

**Comment by Nemant** [comment]
I'm on react native 0.18.1 and nodejs 5.6

**Comment by KyleAMathews** [comment]
This module doesn't work on React Native.

**Comment by Nemant** [comment]
I suspected that. I tried looking online for a similar component but couldn't find anything. Do you have any suggestions?

**Comment by KyleAMathews** [comment]
None that I know of. You could try forking this module and replacing the
LESS stylings with react native styles.
