### ISSUE TITLE
Unusable because of React dependency

### ISSUE THREAD

**Issue by hmeerlo** [mukeshsoni/react-telephone-input#42]
sorry to say but your component is unusable for me (although it looked promising) because it has a direct dependency on react instead of a peerDependency. This makes my app load react twice and it ends up with 'Only a ReactOwner can have refs' errors.

**Comment by mukeshsoni** [comment]
@hmeerlo If i make react a peerdependency, what is the downside?

**Comment by hmeerlo** [comment]
@mukeshsoni There is no real downside, except maybe that the user must explicitly add react as a dependency to his project. But he must do that anyway.

**Comment by mukeshsoni** [comment]
Cool. Have moved react and react-dom to peerDependencies in ver 3.2.3
