### ISSUE TITLE
What about onBlur?

### ISSUE THREAD

**Issue by tonygriv** [mukeshsoni/react-telephone-input#43]
Hello!

Awesome component. But what about onBlur event on input?

**Comment by mukeshsoni** [comment]
Hmm, makes sense. what do you use it for? I wonder why no one asked for it yet.

**Comment by tonygriv** [comment]
For example we send google analytics event on input blur.

**Comment by mukeshsoni** [comment]
@tonygriv Can you send a PR for the adding the feature?

**Comment by mukeshsoni** [comment]
@tonygriv Have added onBlur callback prop in 3.1.3
