### ISSUE TITLE
Exclude built files from repo

### ISSUE THREAD

**Issue by dmnd** [mukeshsoni/react-telephone-input#47]
Having built files in the repo makes diffs sort of confusing. Have you considered adding those directories to gitignore? 

The way I've seen other projects do it is to run a build in prepublish. That way when you publish, you'll be publishing the latest build but don't need it to be checked in.

**Comment by mukeshsoni** [comment]
Have removed the dist folder from repository, now that less file is anyways excluded in the default import.
