### ISSUE TITLE
How do I find out which country code was selected?

### ISSUE THREAD

**Issue by jaredsohn** [mukeshsoni/react-telephone-input#48]
I am using this control for Twilio's API which requires that the country code and phone number are passed in as separate parameters.

If I knew what the country code was, I can find both values.

**Comment by jaredsohn** [comment]
I have a fix for this; will submit a PR when I get a chance (probably tonight.)

**Comment by jaredsohn** [comment]
Pull request here: https://github.com/mukeshsoni/react-telephone-input/pull/50

**Comment by jaredsohn** [comment]
This pull request adds the selected country to onChange and onBlur: https://github.com/mukeshsoni/react-telephone-input/pull/52

**Comment by mukeshsoni** [comment]
Available in 3.2.4 release
