### ISSUE TITLE
Don't warn if preferredCountries is an array of strings

### ISSUE THREAD

**Issue by jaredsohn** [mukeshsoni/react-telephone-input#54]
>        preferredCountries: React.PropTypes.arrayOf(React.PropTypes.object),

I get a warning due to the above line, but it looks like the rest of the code treats preferredCountries as an array of strings.

warning.js:46 Warning: Failed propType: Invalid prop `preferredCountries[0]` of type `string` supplied to `ReactTelephoneInput`, expected `object`

**Comment by mukeshsoni** [comment]
The `preferredCountries` feature is not working anyways. Need to fix the whole thing.

**Comment by jaredsohn** [comment]
That feature actually does work (although it ideally would maintain the order); I think you are thinking of onlyCountries being broken. (There is a comment in the code to that effect.)

**Comment by mukeshsoni** [comment]
Aha! Let me try writing tests for it and check if things are working as expected. I will try and first change the proptype and make a minor release.

**Comment by mukeshsoni** [comment]
@jaredsohn have released v3.4.4 with your pull request. It now expects an array of strings. Thanks!

**Comment by jaredsohn** [comment]
Thanks!
