### ISSUE TITLE
Usage examples in README should mention that preferredCountries is a required prop

### ISSUE THREAD

**Issue by timotgl** [mukeshsoni/react-telephone-input#61]
Just saw that `preferredCountries` does not seem to be included in `getDefaultProps` but is referenced here: https://github.com/mukeshsoni/react-telephone-input/blob/master/lib/ReactTelephoneInput.js#L65

**Comment by msonip** [comment]
Because the preferredCountries implementation is buggy. Didn't want to publish the feature. Will change once it works corretly.

**Comment by timotgl** [comment]
Ok I understand. Just thought I'd open an issue because I tried to use the component but got an exception and had to provide `preferredCountries ` to make it work.

**Comment by mukeshsoni** [comment]
@timotgl Can you give details about the exception? stack trace?

**Comment by timotgl** [comment]
@mukeshsoni Simply use the component without passing `preferredCountries` as a prop and the _.any call in the line I referenced above throws an exception since `this.props.preferredCountries` is `undefined`and not iterable.

**Comment by mukeshsoni** [comment]
@timotgl in v3.4.4 i have added a default prop for preferredCountries (empty array) and will not throw any exceptions even if you don't pass it.
