### ISSUE TITLE
Initial state w/ redux forms

### ISSUE THREAD

**Issue by mbahoshy** [mukeshsoni/react-telephone-input#62]
Great component! however when using this in conjunction with redux-forms, I am unable to set initialValue of component (it is automatically changing input value to '+'). anyone else run into this problem?

**Comment by mukeshsoni** [comment]
@mbahoshy are you passing the initial value to 'value' prop?

**Comment by mbahoshy** [comment]
When using redux forms to set initialValues, the prop for a field ends up looking something like this
`
{ value: "", initialValue: "(555) 555-5555" }
`

I think that to make it more compatible with redux forms, in your getInitialState function change the first line to something like this ...
`
var inputNumber = this.props.initialValue || this.props.value || '';
`

**Comment by mukeshsoni** [comment]
Got it. WIll take a look at redux forms first. Thanks!

**Comment by mukeshsoni** [comment]
@mbahoshy 
I have added it in v3.4.4

**Comment by mbahoshy** [comment]
@mukeshsoni works great with redux forms, thanks!

**Comment by lauterry** [comment]
Hi @marr

I've a problem using with redux 5.x.x.

When I click on a flag, the flag didn't update and the input still display '+'.

Have you encountered this issue ?

**Comment by lauterry** [comment]
Hi

I confirm that the line ``` var inputNumber = this.props.initialValue || this.props.value || '';  ``` introduced a new bug.

When you select a flag, the input value do not update with the country prefix.

After removing ```this.props.initialValue || ```, I have been able to correctly initialize the input value.

I'm using redux-form 5.3.2.

I suggest to revert the change please.

**Comment by mukeshsoni** [comment]
@lauterry I can't remove the initialValue prop now since others might be dependent on it. Need to fix the bug keeping the initialValue prop intact instead
