### ISSUE TITLE
Feature Request: Add an `onFocus` handler to be passed as prop?

### ISSUE THREAD

**Issue by ColmHally** [mukeshsoni/react-telephone-input#64]
Hi,
At the moment, I have no way of knowing when the user has placed their cursor into the telephone input field. Adding an `onFocus` prop (to complement the already-implemented `onBlur` prop) would allow me to track when the user's cursor enters and leaves the input.

Would it be possible to do this?
I can probably submit a pull request to make this easier.
Regards,
Colm

**Comment by mukeshsoni** [comment]
I can accept a pull request if you add a test for it. Thanks

**Comment by ColmHally** [comment]
I'd be happy to add a test but the current tests don't even run!

**Comment by mukeshsoni** [comment]
:) let me make them run. I will ping you.

**Comment by ColmHally** [comment]
Ok, thanks man!
