### ISSUE TITLE
when initialValue or Value is changed in the props

### ISSUE THREAD

**Issue by anilreddykatta** [mukeshsoni/react-telephone-input#66]
Hi Mukesh,

             When I am initializing component for the first time, I am passing a initialValue to the ReactTelephoneInput and it is populating. You are storing the value I am passing in the state after doing formatting in formattedNumber. Issue is when I changed initialValue after some time, then value stored inside state(which is old initialValue) is shown, but not the new initialValue

**Comment by samoshkin** [comment]
Being stuck with the same issue. `props.value` is used to compute `formattedNumber` in `getInitialState` function, but then changes to `props.value` have no effect. There is no `componentWillReceiveProps` or other logic to detect `props.value` changes and to recompute `formattedNumber`. 

The real use case is that I'm not able to reset my form. Telephone input retains its old value, even if I pass empty string in `props.value`.

**Comment by anilreddykatta** [comment]
Can you add componentWillReceiveProps..which checks for oldValue !== newValue and change accordinly..or you can always call let inputNumber = this.props.value || this.state.value || ''. And then this.state.formattedNumber = this.formatNumber(inputNumber)

Writing inside render should be effective strategy..Always giving preference to props instead of just going for state ?

**Comment by mukeshsoni** [comment]
@anilreddykatta @samoshkin Will take a look and try out a solution this weekend

**Comment by anilreddykatta** [comment]
@mukeshsoni  Can you respond to this issue ?

**Comment by mukeshsoni** [comment]
@anilreddykatta I am not able to take time to look into it right now (due to various other things going on in life) and cannot give you tell you when i might be able to. PRs with tests are welcome!

**Comment by mukeshsoni** [comment]
hi @anilreddykatta, i have cut a release '3.5.0' with the changes in the pull request. Can you verify if it works as discussed in this thread?

**Comment by anilreddykatta** [comment]
Thanks @mukeshsoni
