### ISSUE TITLE
Bug for Jamaican Numbers?

### ISSUE THREAD

**Issue by franzejr** [mukeshsoni/react-telephone-input#71]
Hello,

Thanks the library. I think I got a small bug: 

+1 876-211-1821

This is an American Number, but it looks like Jamaican... It should be like this?

**Comment by mukeshsoni** [comment]
looks like jamaican? Is the flag Jamaican? Or should the number be recognized as jamaican?

**Comment by atuttle** [comment]
https://en.wikipedia.org/wiki/Area_code_876

> Area code 876 is the local telephone area code of Jamaica. The 876 area code was created during a split from the original 809 area code. This was done on or around the date May 1997.

If you provide the sample number `+1 876-211-1821` to [the original inspiration](https://github.com/jackocnr/intl-tel-input) for this react component, it also (correctly) interprets this as a Jamaican number.

![image](https://cloud.githubusercontent.com/assets/46990/17118692/bd352078-528f-11e6-8cda-42113d7c66bb.png)

876 is also not on [this list of United States area codes](http://www.allareacodes.com/area_code_listings_by_state.htm), though I'm not sure how up to date it is and they don't provide an updated-timestamp.

**Comment by mukeshsoni** [comment]
@franzejr is it a valid US number?
