### ISSUE TITLE
How to get a name of the input

### ISSUE THREAD

**Issue by Borisboky** [mukeshsoni/react-telephone-input#74]
Hi,

I'm using ReactTelephoneInput.js like a child component. But I would like to validate two input fields with it. I have something like this : 

![screen shot 2016-07-12 at 15 58 36](https://cloud.githubusercontent.com/assets/13819165/16769585/9de7778e-4849-11e6-85c1-e3c8e3fbda5d.png)

And it works for mobilePhone field but I would like to implement it for phone field also. In my main component I have a function with which I set the state of my main component : 

```
setNumber(telNumber, selectedCountry){
        let user = this.state.user;
        const nrFormat = selectedCountry.format;
        const givenNr = telNumber;

        user.mobilePhone = givenNr;


        if(nrFormat){
            if(givenNr.length == nrFormat.length){
                user.mobilePhoneFormat = true;
            }else{
                user.mobilePhoneFormat = false;
                user.mobilePhoneFormatCorrect = nrFormat;
            }
        }else{
            user.mobilePhoneFormat = true;
        }

        this.setState({user: user});

    }
```

Is there any way to do validation of phone field also inside this function? 

And is there any way to add two formats for the same country. For example for Belgium there are mobile numbers in the format +32 ... .. .. .. and the phone numbers are in the format  +32 . ... .. ..

**Comment by mukeshsoni** [comment]
I didn't fully understand but you might want to look at `isValid` prop. You can pass your validation function to `isValid` prop -

```
<ReactTelephoneInput
    isValid={(number) => _.isNumber(number.slice(1))}
    />
```

**Comment by Borisboky** [comment]
I have a form where I have two numbers with the different format. 

![screen shot 2016-09-28 at 10 57 26](https://cloud.githubusercontent.com/assets/13819165/18907085/80985000-856a-11e6-8956-dfcf3ae2cd7c.png)

First field (phone) has format +32 9 266 22 22 and the second field (mobile) has format 
+32 486 33 22 22 . 

In the country_data.js file there is only one format for Belgium

````
[
      'Belgium (België)',
      'be',
      '32',
      '+.. ... .. .. ..'
    ],
````

Thus, that is the format for mobiles. Is there any possibility to add the other one too? And then implement it for the first field (phone) of my form.

Thanks in advance.

**Comment by mukeshsoni** [comment]
It is not supported in the current version. Will label as enhancement.

**Comment by mukeshsoni** [comment]
This should be a change in https://github.com/mukeshsoni/country-telephone-data
