### ISSUE TITLE
How I can use it with requirejs?

### ISSUE THREAD

**Issue by candyboober** [mukeshsoni/react-telephone-input#75]
Hi.
I use django, requirejs, gulp and bower in project.
So I try to load this module async like
```
define(['react-telephone-input'], function(TelInput){
  /* do something */
});

```
and I get an error Uncaught error: Module name .... include require([]);
I try wrap that in r.js -convert, but I get the same error by deps for this plugin.

Thanks for your attention.

**Comment by mukeshsoni** [comment]
@candyboober Can you provide the complete error?

**Comment by mukeshsoni** [comment]
Closing due to lack of data.
