### ISSUE TITLE
Country flags collide when used for multiple lines of phone input.

### ISSUE THREAD

**Issue by milkers** [mukeshsoni/react-telephone-input#76]
One pic worths thousand words, one gif worths thousand pics.
![telinputbug](https://cloud.githubusercontent.com/assets/523525/16947525/4100af30-4db8-11e6-8f3a-d3a7e3c294ce.gif)

Thank you for the project by the way :)

**Comment by milkers** [comment]
default.less file, line 800 need to be updated as `z-index: 15`.

**Comment by mukeshsoni** [comment]
Fixed in 3.6.3 release. Thanks @milkers
