### ISSUE TITLE
Use with Redux-Form

### ISSUE THREAD

**Issue by marr** [mukeshsoni/react-telephone-input#79]
Hi, I am trying to use this with redux form (v6) and having some trouble with propagating errors back up to the form component. It appears that no `name` property is set on the inner `input` of this control. In redux-form we pass in a `name` and set it on the input.

My input is defined like this:
```
const telInput = props => {
  return <ReactTelephoneInput {...props.input} />
}
```

and instantiated like this:
```
 <Field
            classNames="editable-phone"
            component={telInput} name="phoneNumber" id="telInput" flagsImagePath="/images/flags.png"
            preferredCountries={['au', 'gb', 'us', 'nz']} defaultCountry={defaultCountry} />

```
When I reject the submission with Promise.reject, the error does not appear.

**Comment by lauterry** [comment]
Hi @marr 

I've a problem using with redux 5.x.x.

When I click on a flag, the flag didn't update and the input still display +.

Have you encountered this issue ?

**Comment by ForumT** [comment]
Hi,

This issue was closed but i am also facing this problem. I need a way to set name to the inner input because i am dynamically changing values by field name or id.

Any idea how to do it?

**Comment by mukeshsoni** [comment]
you can set any prop on the input by using the `inputProps` prop -
```

<ReactTelephoneInput
    inputProps={{'data-name': 'my_fancy_input'}}
/>
```

**Comment by ForumT** [comment]
Thanks!! :)
