### ISSUE TITLE
Create a display-only version of the component.

### ISSUE THREAD

**Issue by marr** [mukeshsoni/react-telephone-input#80]
It would be nice to have a way to display the formatted phone number for use in a non-edit view.

Would it be possible to export the formatting functionality or a component that would display the formatted number and (optional) country flag?

**Comment by mukeshsoni** [comment]
@marr That's a good idea. I am trying to change the build process to use webpack first. Will take it after i am through with that.

**Comment by marr** [comment]
any movement on this?

**Comment by mukeshsoni** [comment]
@marr  Nope. One workaround is to pass a className and then write css so which disables the textbox and removes the borders so that it looks like a non editable label
