### ISSUE TITLE
number flip

### ISSUE THREAD

**Issue by ellenc345** [mukeshsoni/react-telephone-input#82]
Hey,
when you mark the whole input (including the +) and starting to type a new number
the numbers in places 2 and 3 are jumping to the start of the input.

example: If i type 123
the expected is : +123
what actually happens : +231

Is there a fix for this unwanted behavior?
thanks

**Comment by jaredsohn** [comment]
Try this: https://github.com/mukeshsoni/react-telephone-input/pull/55

**Comment by mukeshsoni** [comment]
Fixed in 3.6.2 with @jaredsohn's PR. Thanks @jaredsohn !
