### ISSUE TITLE
Vertical offset is off when opening the country list

### ISSUE THREAD

**Issue by emwee** [mukeshsoni/react-telephone-input#84]
When I open the country list, the list should jump to the selected country based on the inputted country number, but the vertical offset is off as can be seen in the screenshot below. First I thought this was caused by some custom styling I added but I have removed all custom styling and the issue remains.

My code looks as follows:

```
<ReactTelInput
    defaultCountry={preferredCountries[0]}
    preferredCountries={preferredCountries}
    flagsImagePath='/static/assets/img/checkout/flags.png'
    onChange={(phoneNumber, country) => onChange(phoneNumber, country.name)}
    onBlur={(phoneNumber, country) => onChange(phoneNumber, country.name)}
    value={field.value}
/>
```

![screen shot 2016-09-21 at 2 34 42 pm](https://cloud.githubusercontent.com/assets/1688057/18711080/8f2a20e2-8008-11e6-9df4-023de8c0942c.png)

Thanks in advance!

**Comment by mukeshsoni** [comment]
@emwee I can reproduce it in my local environment nor on the demo page - http://unstack.in/react-telephone-input/

can you give a link to a page? Looks like a css issue.

**Comment by emwee** [comment]
@mukeshsoni I managed to reproduce it by setting the body font size to 16px instead of 14px. Will try to create an isolated example later this week!

**Comment by emwee** [comment]
Ok finally I managed to reproduce the issue! It breaks when the array for `preferredCountries` contains 6 entries! Can you try this?

<img width="232" alt="screen shot 2016-10-24 at 3 06 09 pm" src="https://cloud.githubusercontent.com/assets/1688057/19646726/1e447dc0-99fb-11e6-9cd7-cee2a3ac444a.png">

Otherwise you can try to check out https://github.com/emwee/react-intl-phone-y-offset, run `npm install` and then hit `NODE_ENV=development node_modules/.bin/webpack-dev-server`.

**Comment by mukeshsoni** [comment]
Thanks! Will take a look
