### ISSUE TITLE
file `country_data.js` is missing from npm (~3.7.0)

### ISSUE THREAD

**Issue by iam4x** [mukeshsoni/react-telephone-input#89]
I'm sad since https://github.com/mukeshsoni/react-telephone-input/commit/1414df797b3b7505b1e582ac2f938480af411b05 is a minor update but breaks my build. Should have been pushed with v4.0.0 tag? (I'm here to ask also)

Also it was hard to find out what changes because master does not reflect last version tag :(

**Comment by mukeshsoni** [comment]
The change was that i removed the country_data file and moved it to it's own repo. Don't know how that broke your build but will revert it and push it as a major upgrade.

**Comment by mukeshsoni** [comment]
@iam4x Have reverted the country data file in 3.7.1. Let me know if it works on path upgrade for you.

**Comment by iam4x** [comment]
I use the file `country_data.js` for validating phone number for only the countries we supports on our service:

```jsx
import { some } from 'lodash'
import { allCountries } from 'country-telephone-data'

import { supportedCountries } from 'website-shared/lib/constants'

const allowedCountries = allCountries.filter(({ iso2 }) => supportedCountries.includes(iso2))

export default function(inputNumber) {
  // since we are not checking for existence we return true
  if (!inputNumber) return true
  return some(allowedCountries, (country) => {
    const dialCode = `+${country.dialCode}`
    return inputNumber.startsWith(dialCode) || dialCode.startsWith(inputNumber)
  })
}

export const isFilledPhoneNumber = (inputNumber) => {
  if (inputNumber && inputNumber.length > 1) {
    return some(allowedCountries, (country) => {
      const dialCode = `+${country.dialCode}`
      return inputNumber.startsWith(dialCode) && inputNumber.length > dialCode.length
    })
  }
}
```

Thank's @mukeshsoni 👍

**Comment by mukeshsoni** [comment]
@iam4x  Aha! I suspected people use the country data for other stuff, so forked it into it's own package. Let me know if you face any issues using `country-telephone-data` package. Till today i was the only one using it (and now it's only you :))
