### ISSUE TITLE
Selecting the current country when input is blank does not populate the country code

### ISSUE THREAD

**Issue by gbrassey** [mukeshsoni/react-telephone-input#92]
I just noticed that when a form is empty (either the user removes the input value, or it's a controlled component and initialValue is empty), selecting the current country does not add the country code. 

Seems like if a user deletes all the content and then reselects the current country, for example 'United States', it should populate the input with `+1`.

Add a check [here](https://github.com/mukeshsoni/react-telephone-input/blob/master/src/ReactTelephoneInput.js#L322):

```
if((currentSelectedCountry.iso2 !== nextSelectedCountry.iso2) || this.state.formattedNumber === '+')
```

**Comment by 40818419** [comment]
+1

**Comment by MaxInMoon** [comment]
Works for me with a regular `MobilePhone` field, used with redux-form.


Did you tried to trigger your `onChange` action on `onBlur` handler?

```jsx

const MobilePhone = (props) => {
  const { input, meta, type, placeholder } = props;
  const { value, onChange, onFocus, onBlur } = input;

  const mobilePhone = value;

  return (
    <div className="input-row">
      <ReactTelInput
        value={`${mobilePhone.value}`}
        placeholder={placeholder}
        autoFormat={true}
        defaultCountry={'fr'}
        preferredCountries={['fr', 'gb', 'us']}
        flagsImagePath='/flags.png'
        onFocus={onFocus}
        onChange={(telNumber, selectedCountry) => {
          onChange({
            value: telNumber,
            country: selectedCountry,
          });
        }}
        onBlur={(telNumber, selectedCountry) => {
          onBlur({
            value: telNumber,
            country: selectedCountry,
          });
        }}
      />
    </div>
  );
};
```

**Comment by mukeshsoni** [comment]
@gbrassey can you attach a video or a gif for this one? I could not reproduce it.

**Comment by gbrassey** [comment]
I no longer work on the project that uses this library. Happy to close unless somebody else can replicate.

**Comment by mukeshsoni** [comment]
I will wait for the other person, if any, to reopen it or create a new issue.
