### ISSUE TITLE
Add number formating

### ISSUE THREAD

**Issue by jurgenzz** [mukeshsoni/react-telephone-input#95]
Should we implement functionality, where you can choose the formatting?
At the moment only option - for example for US
`+1 (800) 123-1234`

Should we add options for:

`+1 800-123-1234`and `+1 800 123 1234`

A simple regex will do the trick (tested locally already)

**Comment by mukeshsoni** [comment]
No one has ever asked for such a feature. Don't know what percentage would have this use case.

**Comment by jurgenzz** [comment]
Well, our company work on few different projects for different regions and they like to show different formatting for each one of them. We have a local solution for it at the moment, just checking in if anyone else needs it.

**Comment by mukeshsoni** [comment]
There is a way you can do it in current setup. You can require the countries from country data - 

```
var countryData = require('country-telephone-data')
// make changes to format for countries you want
// pass them as onlyCountries prop
<ReactTelInput onlyCountries={_.filter(_.map(countryData.allCountries, modifyFormat), yourFilter)} />
```

**Comment by mukeshsoni** [comment]
@jurgenzz You can close this issue if the above approach solves your use case.

**Comment by jurgenzz** [comment]
hey, sorry for late answer: 
it works, but it breaks here:

```js
handleFlagItemClick: function handleFlagItemClick(country) {
        var currentSelectedCountry = this.state.selectedCountry;
        var nextSelectedCountry = findWhere(this.props.onlyCountries, country);
``` 

as country now differs from this.props.onlyCountries, for example, US due to different format
