### ISSUE TITLE
add max length prop

### ISSUE THREAD

**Issue by ateyssandier** [mukeshsoni/react-telephone-input#96]
Users should be able to limit the length of the input number for display/api purposes. Add optional param for max length of input. 

-1 if infinite length is allowed

Have this working locally. Can put in a Pull Request.

**Comment by mukeshsoni** [comment]
But why would you want infinite length telephone number?

**Comment by ateyssandier** [comment]
Currently that's what is allowed without the maxLength property.
Default value could also be set to something more reasonable. fifteen? twenty? per here: https://en.wikipedia.org/wiki/Telephone_numbering_plan#International_numbering_plan

**Comment by mukeshsoni** [comment]
Putting these types of restrictions on form elements always come to bite you back. You will anyways knows if the number is not valid. My earlier question was not phrased correctly. What i wanted to ask is "why would the user input infinite length number?". Is there a security vulnerability or does it fail any edge case test scenario?

**Comment by ateyssandier** [comment]
As a rule, users don't always do the right thing. Accidentally copy and pasting a hugely long number for instance. The input currently prohibits the user from inputting non numeric characters in a similar manner, and it seems like adding an (optional) parameter to fail early on validating phone numbers that are too long is a good feature.

**Comment by ricardovj** [comment]
👍  

A "normal" user would NEVER want to input an infinite length number. A rogue user can currently come in and paste 1MB worth of plain text numbers in an attempt to find vulnerabilities in your service.

**Comment by mukeshsoni** [comment]
@ateyssandier The chance of a user typing a non numeric character is much bigger than a user copy pasting a huge string. I would wait on this one until i see a number of people wanting it.

@ricardovj 
If there are vulnerabilities, you are better off finding them.

**Comment by nmartinezb3** [comment]
@mukeshsoni are you still not supporting max length?
